preload=~/.config/hypr/backgrounds/BackgroundLeft.png
preload=~/.config/hypr/backgrounds/BackgroundMiddle.png
preload=~/.config/hypr/backgrounds/BackgroundRight.png
preload=~/.config/hypr/backgrounds/CelesteMiddle.png
preload=~/.config/hypr/backgrounds/CelesteLeft.png
preload=~/.config/hypr/backgrounds/CelesteHDHeart.png

# wallpaper = DVI-D-1,~/.config/hypr/backgrounds/BackgroundLeft.png
# wallpaper = DP-1,~/.config/hypr/backgrounds/BackgroundMiddle.png
# wallpaper = HDMI-A-1,~/.config/hypr/backgrounds/BackgroundRight.png
# wallpaper = HDMI-A-2,~/.config/hypr/backgrounds/BackgroundLeft.png
# wallpaper = eDP-1,~/.config/hypr/backgrounds/BackgroundMiddle.png

# wallpaper = eDP-1,~/.config/hypr/backgrounds/CelesteLeft.png
wallpaper = eDP-1,~/.config/hypr/backgrounds/CelesteHDHeart.png
# wallpaper = DP-1,~/.config/hypr/backgrounds/CelesteMiddle.png
wallpaper = DP-1,~/.config/hypr/backgrounds/CelesteHDHeart.png
wallpaper = HDMI-A-2,~/.config/hypr/backgrounds/CelesteLeft.png
